version: '3.1'
services:

  wildfly:
    image: jboss-application
    ports:
      - '8080:8080'
      - '9990:9990'
    command: /opt/jboss/wildfly/bin/standalone.sh --server-config=configuration.xml -b 0.0.0.0 -bmanagement 0.0.0.0

volumes:
  wildfly_log:
    driver: local
