version: '3.1'
services:

  wildfly:
    image: jboss-application
    ports:
      - '8080:8080'
    volumes:
      - './configuration.xml:/opt/jboss/wildfly/standalone/configuration/configuration.xml'
    command: /opt/jboss/wildfly/bin/standalone.sh --server-config=configuration.xml -b 0.0.0.0