version: '3.1'

#-------------------------------
# Volume Shared between JBoss/Filebeat/Busybox
#-------------------------------
volumes:
  wildfly_log:
    driver: local

services:

  #-------------------------------
  # JBoss + Application 
  #-------------------------------
  wildfly:
    image: jboss-application
    ports:
      - '8080:8080'
    volumes:
      - 'wildfly_log:/opt/jboss/wildfly/standalone/log'
      - './configuration.xml:/opt/jboss/wildfly/standalone/configuration/configuration.xml:ro'
      - './my.properties:/opt/jboss/wildfly/standalone/configuration/my.properties:ro'
    command: /opt/jboss/wildfly/bin/standalone.sh --server-config=configuration.xml -b 0.0.0.0 -bmanagement 0.0.0.0
    depends_on: ['permission']

  #-------------------------------
  # Filebeat send all logs to Elastic
  #-------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    restart: always
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    depends_on: ['wildfly']
    volumes:
      - 'wildfly_log:/mnt/log:ro'
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  #-------------------------------
  # Open JBoss log directory to everybody
  #-------------------------------
  permission:
    image: 'busybox'    
    volumes:
      - 'wildfly_log:/opt/jboss/wildfly/standalone/log'
    command: chmod 777 /opt/jboss/wildfly/standalone/log

#-------------------------------
# Link default network to the network
# of Elastic Stack
#-------------------------------
networks:
  default:
    external:
      name: stack-docker_stack

secrets:
  filebeat.yml:
    file: ./filebeat.yml

